default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: pos_qr_system_test

production:
  <<: *default
  database: pos_qr_system_production
  username: pos_qr_system
  password: <%= ENV["POS_QR_SYSTEM_DATABASE_PASSWORD"] %>
